#!/bin/sh


/bin/echo "########################## Backing up local ~/Music directory to strongspace #############################" && \
#scp -r ~/Music/* chriswinn@strongspace.com:music/ && \
rsync -avz --delete --force ~/Music/Max/ chriswinn@chriswinn.strongspace.com:music/Max && \

/bin/echo "########################## Finished Backing up local ~/Music directory to strongspace #############################"


